// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaenhU2Tm09bNzibfFPiZY8cpnBHKcrLA',
    appId: '1:334457579966:web:39a88b34111a60cdbb31ef',
    messagingSenderId: '334457579966',
    projectId: 'flutter-12bbc',
    authDomain: 'flutter-12bbc.firebaseapp.com',
    storageBucket: 'flutter-12bbc.appspot.com',
    measurementId: 'G-2ZPQ20CEY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYGHsAENyt1E-jredKPy_ZOAkziSswV1c',
    appId: '1:334457579966:android:a8d03eac55f6b106bb31ef',
    messagingSenderId: '334457579966',
    projectId: 'flutter-12bbc',
    storageBucket: 'flutter-12bbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlZrtkX0vmTzHUG3vki-2fkcx_UiMx6Q',
    appId: '1:334457579966:ios:e05dce760c1d4477bb31ef',
    messagingSenderId: '334457579966',
    projectId: 'flutter-12bbc',
    storageBucket: 'flutter-12bbc.appspot.com',
    iosBundleId: 'com.example.firebasetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlZrtkX0vmTzHUG3vki-2fkcx_UiMx6Q',
    appId: '1:334457579966:ios:59bf71768f835568bb31ef',
    messagingSenderId: '334457579966',
    projectId: 'flutter-12bbc',
    storageBucket: 'flutter-12bbc.appspot.com',
    iosBundleId: 'com.example.firebasetest.RunnerTests',
  );
}
